### ISSUE TITLE
Tillad upload af større filer.

### ISSUE THREAD

**Issue by LarsIlver** [cphflacour/open-data-dk#15]
CKAN tillader ikke upload af filer over 20Mb.
Der er aktuelt i Odense behov for upload af filer større end 20Mb.

**Comment by LarsIlver** [comment]
Har rettet /etc/ckan/default/production.ini

Fra:
#ckan.storage_path = /var/lib/ckan
ckan.storage_path = /var/lib/ckan/default
ckan.max_resource_size = 20
#ckan.max_image_size = 2
Til:
#ckan.storage_path = /var/lib/ckan
ckan.storage_path = /var/lib/ckan/default
ckan.max_resource_size = 250
#ckan.max_image_size = 2

Der mangler nu kun en "sudo service apache 2 reload"

**Comment by cphflacour** [comment]
Restarted
