### ISSUE TITLE
Problemer med geojson vieweren

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#16]

**Comment by cphflacour** [comment]
Hej Opendata,

Vores udvikler efterspørger plugins i Open Data DK’s CKAN – se nederfor:


Opendata.dk's CKAN har ikke en række plugins aktiveret. GC2 forsøger at oprette HTML og GeoJSON views for hvert datasæt, men det mislykkes.

Eksempler på views:

HTML
http://geofyn-ckan.mapcentia.com/dataset/d1968db5-63ca-4f3f-b18a-47be53af7b66/resource/d1968db5-63ca-4f3f-b18a-47be53af7b66-html

GeoJSON
http://geofyn-ckan.mapcentia.com/dataset/d1968db5-63ca-4f3f-b18a-47be53af7b66/resource/d1968db5-63ca-4f3f-b18a-47be53af7b66-geojson

Begge er standard plugins, som følger med CKAN. Det kunne være, at I skulle spørge opendata.dk om de ikke kan aktivere disse to plugins.



Er det noget der kan blive aktiveret?

Vh. Anders Barfod
Ballerup Kommune
41750135

**Comment by NicolaiLolansen** [comment]
Det skulle ikke være et problem at sætte op, jeg troede i virkeligheden at de var slået til.

**Comment by cphflacour** [comment]
Lavede vi et fix på data.kk.dk. Der var noget med at rettigheder eller api blev ændret?

Kan vi overføre dette fix og det lækre kort?

**Comment by NicolaiLolansen** [comment]
Kortet dækker kun København og forudsætter at data kommer fra en WMS service. Men vi kan nok godt lave noget lignende

**Comment by cphflacour** [comment]
http://www.viderum.com/blog/2016/07/12/fixing-spartial-maps-in-CKAN

**Comment by cphflacour** [comment]
Emne: Eksempelvisning på opendata.dk

Hej Birgitte,

For datasæt på odaa.dk og data.kk.dk har jeg bemærket, at det er muligt at få en eksempel/forhåndsvisning af datasæt. Tilsvarende ser ikke ud til at fungere på opendata.dk. Er det noget I/jeres tekniker er opmærksom på?

Se fx:
http://data.kk.dk/dataset/parkeringshuse/resource/373033a8-6e7c-4d74-924d-82119d8251d7
http://portal.opendata.dk/dataset/parkeringshuse/resource/373033a8-6e7c-4d74-924d-82119d8251d7
og
https://www.odaa.dk/dataset/hundeskove-i-aarhus/resource/e220e1a7-7392-483f-9db5-f3eee91b4e8f
http://portal.opendata.dk/dataset/hundeskove-i-aarhus/resource/e220e1a7-7392-483f-9db5-f3eee91b4e8f

**Comment by NicolaiLolansen** [comment]
Århus geojson typer registreres ikke af plugin. Har kontaktet Steen Gert, ellers må vi se om vi kan lave et fix. For alle andre datasæt burde det fungere
