### ISSUE TITLE
Aktivering af HTML-viewer

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#17]

**Comment by cphflacour** [comment]
Hej Opendata,

Vores udvikler efterspørger plugins i Open Data DK’s CKAN – se nederfor:


Opendata.dk's CKAN har ikke en række plugins aktiveret. GC2 forsøger at oprette HTML og GeoJSON views for hvert datasæt, men det mislykkes.

Eksempler på views:

HTML
http://geofyn-ckan.mapcentia.com/dataset/d1968db5-63ca-4f3f-b18a-47be53af7b66/resource/d1968db5-63ca-4f3f-b18a-47be53af7b66-html

GeoJSON
http://geofyn-ckan.mapcentia.com/dataset/d1968db5-63ca-4f3f-b18a-47be53af7b66/resource/d1968db5-63ca-4f3f-b18a-47be53af7b66-geojson

Begge er standard plugins, som følger med CKAN. Det kunne være, at I skulle spørge opendata.dk om de ikke kan aktivere disse to plugins.



Er det noget der kan blive aktiveret?

**Comment by NicolaiLolansen** [comment]
Det er implementeret. Århus har problemer med deres "geojson" type i CKAN, har informeret Steen, og så må vi se om vi ikke lige kan få løst det. HTML og GeoJSON er aktiveret på opendata.dk
