### ISSUE TITLE
Mulighed for webpages

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#19]
For eksempel gennem extension simple-cms

**Comment by cphflacour** [comment]
vi har en enorm stor kommunikationsopgave overfor vores medlemmer ift. formater, metadata osv. i forbindelse med at lægge data på platformen. 

I den forbindelse tænkte jeg på, om det er muligt på portal.opendata.dk at lave et ekstra punkt i topmenuen, der evt. hedder vejledninger. 
Lidt a la inspirations-punktet som Aalborg har lavet på deres site: http://www.odlaa.dk/pages/inspiration
Der kan vi lægge metadata-skabelon ind, whitepaperet, beslutning om de 5-10 ens datasæt, når den beslutning er truffet osv.

**Comment by NicolaiLolansen** [comment]
Emil har lagt på. Hvis man har rettigheder kan man redigere pages via http://portal.opendata.dk/pages
