### ISSUE TITLE
Søgemaskineoptimering

### ISSUE THREAD

**Issue by AEPSchmitt** [cphflacour/open-data-dk#21]
Perfekte søgematches opdages ikke ved søgning, samt problemer ved søgninger på 2 tegn.

**Comment by AEPSchmitt** [comment]
Fx finder en søgning på 'driftsområder' ingenting:
![image](https://cloud.githubusercontent.com/assets/9079958/21216591/ea6aff76-c2a7-11e6-925b-e3e47f2c6836.png)

På trods af datasættet eksisterer med præcis det navn der søges på:
![image](https://cloud.githubusercontent.com/assets/9079958/21216615/0e93ff1a-c2a8-11e6-9fd8-2e2bc925b5b0.png)

**Comment by cphflacour** [comment]
Er det ÆØÅ-problematik?

**Comment by AEPSchmitt** [comment]
Ingen ÆØÅ-problemer så vidt jeg kan se, men der er problemer med:
- Store/små bogstaver (jeg finder ovenstående driftsområder hvis jeg skifter startbogstav til stort).
- Ord på 2 bogstaver. Det er problematisk at finde fx "Sø". Det skyldes den måde søgealgoritmen "stemmer" ord til deres rodform.
- Datasæt med bindestreg, søges der direkte på et navn med bindestreg, tolkes bindestregen som "ignorér næste ord".
