### ISSUE TITLE
Advisering fra CKAN, hvis datasæt er nede

### ISSUE THREAD

**Issue by bikj** [cphflacour/open-data-dk#24]
Hej teknikteam

Er det muligt, at kontaktpersonen på et datasæt kan få en advisering, hvis et datasæt er nede?
Det er et ønske fra flere kommuner.

**Comment by ilver** [comment]
Et datasæt kan være utilgængeligt pga. en eller flere forudsætninger for visning af datasæt er nede.
Det giver begrænset mening at informere om aktuelle driftfejl til brugere, der alligevel ikke kan gøre noget ved det.
opendata.dk bør fokusere på etablering af stabil platform og et solid driftsetup.
-Og burde månedligt give feed back til diverse kommuner om interessse for de data de har udstillet og fakta om drift. Mht sidtsnævnte ville det være meget professionelt hvis opendata.dk definerer den SLA Kommuner kan forvente, og at det som del af månedligt feedback også evalueres om SLA er indfriet.
