### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#3]
Oprettelse af SSL Certificat fra https://letsencrypt.org/

**Comment by ilver** [comment]
I forbindelse med ny server har jeg prøvet at lægge SSL på. Min vurdering er at CKAN som en node, der både har interne og eksterne kilder, giver slutbrugeren et dårligt indtryk, da besked om at der er tale om usikre kilder popper op konstant.
Samtidig har CKAN tilsyneladende en del afgørende intern kode, der fejler fordi URL'er ikke er https, eksempelvis når Leaflet bruges til preview, så går den i stå.
Min konklusion for nu, er at SSL er fint for enkelt kilde, men er der tale om Comprehensive Knowledge Archive Network (CKAN), så er SSL ikke en god ide.
/Lars

**Comment by cphflacour** [comment]
Jep, det tyder på at det er mere kompliceret end som så. Så den er ikke Ready.

Men det er dog stadig et væsentligt ønske.

Vi må holde øje med udviklingen og rykke når det er mere modent.

**Comment by bikj** [comment]
Hej. Har I snakket med Steen om den her? Vi har SSL på www.odaa.dk. Hvordan han har gjort, ved jeg ikke. Men det er da en mulighed for jer at spørge ham.
/Birgitte

**Comment by cphflacour** [comment]
Virker på https://test.opendata.dk

Er igangsat på prod
