### ISSUE TITLE
Statistik på dataplatformen

### ISSUE THREAD

**Issue by bikj** [cphflacour/open-data-dk#40]
Meget høj prioritet!
Der efterspørges i høj grad mere statistik på platformen. 
Statistik om antal downloads og antal kald via API.

**Comment by LarsIlver** [comment]
Vanskeligt med API kald.
Robotter og crawlere fylder meget og er svære at indentificere/udelukke.

Det vil nok kræve en bruger/token dimension i CKAN før reelle API kal kan identificeres.

/Lars

Fra: bikj [mailto:notifications@github.com]
Sendt: 16. marts 2018 08:01
Til: cphflacour/open-data-dk <open-data-dk@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [cphflacour/open-data-dk] Statistik på dataplatformen (#40)


Meget høj prioritet!
Der efterspørges i høj grad mere statistik på platformen.
Statistik om antal downloads og antal kald via API.
