### ISSUE TITLE
Google Analytics data tilgængelige på portalen

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#8]

**Comment by bikj** [comment]
Hej Frans og alle
I Aarhus har vi udviklet et statistik-modul til CKAN. Det ligger åbent tilgængelig på github (https://github.com/OpenDataAarhus/LogStatistik). Kunne det være en mulighed at implementere det på portal.opendata.dk også?
Vi har et offentligt tilgængeligt datasæt på www.odaa.dk med statistik om siden. I kan se det her https://www.odaa.dk/dataset/statistik-pa-odaa. Dataejerne er ret glade for det.

**Comment by cphflacour** [comment]
Strålende forslag - jeg har lagt den på som selvstændigt issue. Da det ikke behøver at være enten eller.

**Comment by cphflacour** [comment]
Google er måske ikke den bedste platform for dette. Se issue #28
