### ISSUE TITLE
Brugsstatistik på portal

### ISSUE THREAD

**Issue by cphflacour** [cphflacour/open-data-dk#9]
Hej Frans og alle
I Aarhus har vi udviklet et statistik-modul til CKAN. Det ligger åbent tilgængelig på github (https://github.com/OpenDataAarhus/LogStatistik). Kunne det være en mulighed at implementere det på portal.opendata.dk også?
Vi har et offentligt tilgængeligt datasæt på www.odaa.dk med statistik om siden. I kan se det her https://www.odaa.dk/dataset/statistik-pa-odaa. Dataejerne er ret glade for det.

**Comment by cphflacour** [comment]
Umiddelbart tror jeg det ville være mere hensigtsmæssigt at bruge 

https://github.com/NicolaiMogensen/ckanext-updatetracking

**Comment by cphflacour** [comment]
Hej Lars

Nåede du videre med dette?

**Comment by NicolaiLolansen** [comment]
Hvis det er kan jeg sagtens implementere samme løsning som vi har lavet i København, som Frans også har  linket tidligere.

**Comment by bikj** [comment]
Beklager, at jeg igen igen blander mig herinde.... Men som jeg kan se det ud fra statistik-datasættet på data.kk.dk trackes der kun besøg på datasættet. Er det ikke relevant at tracke download/API-kald også? Det viser trods alt, at data faktisk er hentet og ikke bare kigget på. Måske der er nogle tekniske argumenter for, at det ikke er vigtigt....Dem kender I sikkert:-)

**Comment by NicolaiLolansen** [comment]
Jeg tror at mit problem i sin tid var at jeg ikke kunne se om det var en unik bruger der lavede kaldet, da CKAN selv går ud og ind igennem HTTP. Jeg tror ikke CKAN loggen er stærk nok til at den slags statistik kan give mening (Men jeg kan undersøge det), da et enkelt eksternt job kan stå for en stor del af kaldene. Det kan være jeg skal åbne op i maskineriet igen og se om der kan være en anden løsning.

Den slags data ville være relevante hvis det er muligt at bestemme hvor mange unikke brugere der er.
